version: "3.9"

services:
  vireoka_db:
    image: mariadb:10.6
    container_name: vireoka_db
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped

  vireoka_wp:
    image: wordpress:php8.2-apache
    container_name: vireoka_wp
    ports:
      - "8085:80"
    environment:
      WORDPRESS_DB_HOST: vireoka_db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp:/var/www/html
    depends_on:
      - vireoka_db
    restart: unless-stopped

volumes:
  db_data:
